groups:
  - name: infrastructure.rules
    rules:
      - alert: HostDown
        expr: up{job=~"personal|startup"} == 0
        for: 2m
        labels:
          severity: critical
          component: "infrastructure"
        annotations:
          summary: "Host {{ $labels.instance }} is unreachable"
          description: "Host {{ $labels.instance }} has been down for more than 2 minutes"
          
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 1m
        labels:
          severity: warning
          component: "infrastructure"
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: 'CPU usage is {{ printf "%.1f" $value }}% for more than 1 minute'
          
      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 30s
        labels:
          severity: critical
          component: "infrastructure"
        annotations:
          summary: "Critical CPU usage on {{ $labels.instance }}"
          description: 'CPU usage is {{ printf "%.1f" $value }}% for more than 30 seconds'
          
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 75
        for: 1m
        labels:
          severity: warning
          component: "infrastructure"
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: 'Memory usage is {{ printf "%.1f" $value }}% for more than 1 minute'
          
      - alert: CriticalMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 0m
        labels:
          severity: critical
          component: "infrastructure"
        annotations:
          summary: "Critical memory usage on {{ $labels.instance }}"
          description: 'Memory usage is {{ printf "%.1f" $value }}% - immediate alert!'
          
      - alert: DiskSpaceCritical
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 95
        for: 1m
        labels:
          severity: critical
          component: "infrastructure"
        annotations:
          summary: "Critical disk space on {{ $labels.instance }}"
          description: 'Disk usage is {{ printf "%.1f" $value }}% on {{ $labels.mountpoint }}'
          
      - alert: DiskSpaceWarning
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
          component: "infrastructure"
        annotations:
          summary: "High disk space on {{ $labels.instance }}"
          description: 'Disk usage is {{ printf "%.1f" $value }}% on {{ $labels.mountpoint }}'